version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:14
    steps:
        - checkout
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
        - restore_cache:
            key: dependency-cache-{{checksum "package-lock.json"}}
        - run:
            name: install-npm
            command: npm install
        - run:
            name: run-tests
            command: npm test  
        - save_cache:
            key: dependency-cache-{{checksum "package-lock.json"}}
            paths:
              - ./node_modules
        - store_test_results:
           path: test-results
        - store_artifacts:
           path: test-artifacts  
workflows:
  build_tests:
    jobs:
      - run_tests
