import { ThemeProvider } from "@/components/theme-provider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - SamuelNayo",
    template: "%s | Next.js Tutorial - SamuelNayo",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
          <header
            style={{
              background: "lightgray", 
              padding: "1rem"
            }}
            >
              <p>Header</p>
          </header>
            {children}
          <footer
            style={{
              backgroundColor: "ghostwhite",
              padding: "1rem"
            }}
            >
            Footer
          </footer>
        </body>
      </ThemeProvider>
    </html>
  )
}