import { Metadata } from "next";
// import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - SamuelNayo",
    template: "%s | Next.js Tutorial - SamuelNayo",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            background: "lightgray", 
            padding: "1rem"
          }}
        >
            <p>Header</p>
        </header>

        {/* <ErrorWrapper> */}
          {children}
        {/* </ErrorWrapper> */}

        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem"
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  )
}