export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem"
          }}
          >
          <p>Marketing Header</p>
        </header>

        {children}

        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem"
          }}
          >
            <p>Marketing Footer</p>
        </footer>
      </body>
    </html>
  );
}
